name: Sync Migu JSON

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Download and process
      run: |
        curl -s -o input.txt https://raw.githubusercontent.com/develop202/migu_video/main/interface.txt
        echo "{" > migu.json
        first=1
        while read line; do
          if [[ $line == *"svg-name="* ]]; then
            name=$(echo $line | grep -o 'svg-name="[^"]*"' | cut -d'"' -f2)
          elif [[ $line == http* && -n $name ]]; then
            if [ $first -eq 0 ]; then echo "," >> migu.json; fi
            echo "  \"$name\": \"$line\"" >> migu.json
            first=0
            name=""
          fi
        done < input.txt
        echo "}" >> migu.json
        rm input.txt

    - name: Commit
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add migu.json
        if ! git diff --cached --quiet; then
          git commit -m "Update $(date '+%Y-%m-%d %H:%M')"
          git push origin main
        fi
