name: Sync Migu JSON Hourly

on:
  schedule:
    - cron: '0 * * * *' # 每小时运行一次
  workflow_dispatch:

jobs:
  update-migu-json:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ 检出 GitHub 仓库
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      # 2️⃣ 下载 interface.txt
      - name: Download interface.txt
        run: |
          curl -sSL -o interface.txt "https://raw.githubusercontent.com/develop202/migu_video/refs/heads/main/interface.txt"
          if [ ! -s interface.txt ]; then
            echo "Failed to download interface.txt"
            exit 1
          fi
          echo "Downloaded interface.txt successfully"
          echo "First few lines:"
          head -3 interface.txt

      # 3️⃣ 解析 M3U 并生成 migu.json
      - name: Convert M3U to JSON
        run: |
          python3 << 'EOF'
import re
import json

# 读取 M3U 文件
with open('interface.txt', 'r', encoding='utf-8') as f:
    lines = f.readlines()

channels = {}
current_name = None

for line in lines:
    line = line.strip()
    
    # 跳过 M3U 头信息和空行
    if line.startswith('#EXTM3U') or not line:
        continue
    
    # 解析频道信息行
    if line.startswith('#EXTINF:'):
        # 使用正则表达式提取 svg-name
        name_match = re.search(r'svg-name="([^"]+)"', line)
        if name_match:
            current_name = name_match.group(1)
        else:
            # 如果找不到 svg-name，尝试从频道名称部分提取
            name_match = re.search(r',([^,]+)$', line)
            if name_match:
                current_name = name_match.group(1).strip()
    
    # 解析 URL 行
    elif line.startswith('http'):
        if current_name:
            # 清理 URL（移除可能的时间戳参数）
            url = re.sub(r'(&?timestamp=\d+)', '', line)
            url = re.sub(r'(&?SecurityKey=\d+)', '', url)
            channels[current_name] = url
            current_name = None

print(f"成功解析 {len(channels)} 个频道")

# 保存为 JSON 文件
with open('migu.json', 'w', encoding='utf-8') as f:
    json.dump(channels, f, ensure_ascii=False, indent=2)

print("migu.json 文件已生成")
EOF

      # 4️⃣ 验证生成的 JSON 文件
      - name: Validate JSON
        run: |
          echo "生成的 JSON 文件前几个频道:"
          head -10 migu.json
          echo "总频道数: $(jq 'length' migu.json)"
          echo "示例频道:"
          jq 'to_entries | .[0:2] | from_entries' migu.json

      # 5️⃣ 提交并推送更改
      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add migu.json
          
          if git diff --cached --quiet; then
            echo "没有变化需要提交"
          else
            echo "检测到变化，提交并推送"
            git status
            NOW=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')
            git commit -m "🔄 自动更新 migu.json [$NOW]"
            git push origin main
            echo "更改已推送"
          fi

      # 6️⃣ 清理临时文件
      - name: Clean up
        run: |
          rm -f interface.txt
          echo "临时文件已清理"
