name: Sync Github MiguJSON

on:
  schedule:
    - cron: '0 */2 * * *' # 每 2 小时 UTC 执行一次
  workflow_dispatch:

jobs:
  sync-migu-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Download interface.txt
        run: |
          curl -sSL -o interface.txt https://raw.githubusercontent.com/develop202/migu_video/refs/heads/main/interface.txt
          if [ ! -s interface.txt ]; then
            echo "Failed to download interface.txt"
            exit 1
          fi

      - name: Convert M3U to JSON
        run: |
          python3 - <<'EOF'
import re, json

m3u_file = "interface.txt"
json_file = "migu.json"

channels = {}
with open(m3u_file, "r", encoding="utf-8") as f:
    lines = f.readlines()

name = None
for line in lines:
    line = line.strip()
    if line.startswith("#EXTINF:"):
        match = re.search(r'svg-name="([^"]+)"', line)
        if match:
            name = match.group(1)
    elif line and not line.startswith("#"):
        if name:
            channels[name] = line
            name = None

with open(json_file, "w", encoding="utf-8") as f:
    json.dump(channels, f, ensure_ascii=False, indent=2)
EOF

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add migu.json
          if ! git diff --cached --quiet; then
            NOW=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')
            git commit -m "Update migu.json from interface.txt [$NOW]"
            git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/hxfkofoutlook/iptv.git main
          else
            echo "No changes to commit"
