name: Sync Gitee Migu Files (Lightweight)

on:
  schedule:
    - cron: "0 */2 * * *"  # 每 2 小时同步一次
  workflow_dispatch:       # 支持手动触发

jobs:
  sync-files:
    runs-on: ubuntu-latest
    steps:
      # 检出 GitHub 仓库
      - name: Checkout GitHub repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # 不使用默认 token

      # 配置 Git 用户信息
      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"

      # 从 Gitee 下载指定文件
      - name: Download files from Gitee
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
        run: |
          curl -sL -o migu.json "https://$GITEE_TOKEN@gitee.com/hxfrock/migu_video/raw/main/migu.json"
          curl -sL -o miguepg.xml "https://$GITEE_TOKEN@gitee.com/hxfrock/migu_video/raw/main/miguepg.xml"

      # 提交并 push 到 GitHub（仅当文件有变化时）
      - name: Commit and push to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add migu.json miguepg.xml
          git diff --quiet && git diff --staged --quiet || git commit -m "Update migu.json & miguepg.xml from Gitee"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/hxfkofoutlook/iptv.git main

