name: Sync Migu JSON Hourly

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-migu-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Download interface.txt
        run: |
          curl -sSL -o interface.txt "https://raw.githubusercontent.com/develop202/migu_video/refs/heads/main/interface.txt"
          if [ ! -s interface.txt ]; then
            echo "Failed to download interface.txt"
            exit 1
          fi

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Convert M3U to JSON
        run: |
          echo "{" > migu.json
          first_entry=true
          current_name=""
          
          while IFS= read -r line; do
            # Skip header lines
            if [[ "$line" == "#EXTM3U"* ]]; then
              continue
            fi
            
            # Extract channel name
            if [[ "$line" == "#EXTINF:"* ]] && [[ "$line" == *"svg-name="* ]]; then
              current_name=$(echo "$line" | grep -o 'svg-name="[^"]*"' | cut -d'"' -f2)
            fi
            
            # Extract URL and write to JSON
            if [[ "$line" == http* ]] && [[ -n "$current_name" ]]; then
              if [ "$first_entry" = false ]; then
                echo "," >> migu.json
              fi
              escaped_name=$(echo "$current_name" | sed 's/"/\\"/g')
              echo "  \"$escaped_name\": \"$line\"" >> migu.json
              first_entry=false
              current_name=""
            fi
          done < interface.txt
          
          echo "}" >> migu.json

      - name: Validate JSON
        run: |
          if jq empty migu.json >/dev/null 2>&1; then
            echo "JSON validation passed"
            echo "Total channels: $(jq 'length' migu.json)"
          else
            echo "JSON validation failed"
            exit 1
          fi

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add migu.json
          if ! git diff --cached --quiet; then
            NOW=$(date '+%Y-%m-%d %H:%M:%S')
            git commit -m "Update migu.json [$NOW]"
            git push origin main
          else
            echo "No changes to commit"
          fi

      - name: Clean up
        run: rm -f interface.txt
