name: Sync migu EPG XML

on:
  schedule:
    - cron: '0 */2 * * *'  # 每 2 小时执行一次 UTC
  workflow_dispatch:

jobs:
  sync-epg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Download EPG XML
        run: |
          curl -sSL -o miguepg.xml https://raw.githubusercontent.com/develop202/migu_video/refs/heads/main/playback.xml
          if [ ! -s miguepg.xml ]; then
            echo "EPG download failed"
            exit 1
          fi

      - name: Modify <tv> tag
        run: |
          sed -i 's|<tv generator-info-name="Tak" generator-info-url="https://github.com/develop202/migu_video/">|<tv generator-info-name="Migu" generator-info-url="https://mytveo.hxfkof.ggff.net/?proxy=true">|' miguepg.xml

      - name: Commit & Push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add miguepg.xml
          if ! git diff --cached --quiet; then
            NOW=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')
            git commit -m "Update miguepg.xml - $NOW"
            git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/hxfkofoutlook/iptv.git main
          else
            echo "No changes to commit"
          fi
