# 从 Gitee 下载文件（使用API方式）
- name: Download files from Gitee via API
  env:
    GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
  run: |
    # 安装 jq 用于 JSON 解析
    sudo apt-get install -y jq
    
    download_via_api() {
      local repo_owner="hxfrock"
      local repo_name="migu_video"
      local file_path=$1
      local output_file=$2
      local max_attempts=3
      local attempt=1
      
      while [ $attempt -le $max_attempts ]; do
        echo "Attempt $attempt: Downloading $file_path via API"
        
        # 使用 Gitee API 获取文件内容
        api_url="https://gitee.com/api/v5/repos/$repo_owner/$repo_name/contents/$file_path"
        
        if response=$(curl -sL -H "Authorization: token $GITEE_TOKEN" "$api_url"); then
          # 解析 JSON 并解码 base64 内容
          content=$(echo "$response" | jq -r '.content' 2>/dev/null)
          if [ "$content" != "null" ] && [ -n "$content" ]; then
            echo "$content" | base64 -d > "$output_file"
            if [ -s "$output_file" ]; then
              echo "Successfully downloaded $output_file via API"
              return 0
            fi
          fi
        fi
        
        echo "API download failed, retrying in 5 seconds..."
        sleep 5
        attempt=$((attempt + 1))
      done
      echo "Failed to download $output_file via API after $max_attempts attempts"
      return 1
    }
    
    download_via_api "migu.json" "migu.json"
    download_via_api "miguepg.xml" "miguepg.xml"
