name: Sync Gitee Files (Lightweight)

on:
  schedule:
    - cron: "0 */2 * * *"  # 每 2 小时
  workflow_dispatch:

jobs:
  sync-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"

      - name: Download files from Gitee
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
        run: |
          curl -sL -o migu.json "https://$GITEE_TOKEN@gitee.com/hxfrock/iptv/raw/main/migu.json"
          curl -sL -o miguepg.xml "https://$GITEE_TOKEN@gitee.com/hxfrock/iptv/raw/main/miguepg.xml"

      - name: Commit and push to GitHub
        run: |
          git add migu.json miguepg.xml
          git diff --quiet && git diff --staged --quiet || git commit -m "Update migu.json & miguepg.xml from Gitee"
          git push
