name: Sync Migu JSON Hourly

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-migu-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Download interface.txt
        run: curl -s -o interface.txt "https://raw.githubusercontent.com/develop202/migu_video/main/interface.txt"

      - name: Convert M3U to JSON
        run: |
          echo "{" > migu.json
          first=1
          name=""
          while IFS= read -r line; do
            if echo "$line" | grep -q "svg-name="; then
              name=$(echo "$line" | grep -o 'svg-name="[^"]*"' | cut -d'"' -f2)
            elif echo "$line" | grep -q "^http"; then
              if [ -n "$name" ]; then
                if [ $first -eq 0 ]; then
                  echo "," >> migu.json
                fi
                echo "  \"$name\": \"$line\"" >> migu.json
                first=0
                name=""
              fi
            fi
          done < interface.txt
          echo "}" >> migu.json

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add migu.json
          if ! git diff --cached --quiet; then
            git commit -m "Update migu.json $(date '+%Y-%m-%d %H:%M:%S')"
            git push origin main
          fi

      - name: Clean up
        run: rm -f interface.txt
